backend:
  name: github
  branch: master
  repo: tcovington1/CodeWithTaylor-blog

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Slug", name: "slug", widget: "string", default: " "}
      - {label: "Publish Date", name: "date", widget: "string", default: " "}
      - {label: "Title", name: "title", widget: "string", default: " "}
      # - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
